"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var message = 'Hello world!';
console.log(message);
var name;
name = "islomjon";
console.log(name);
var lastname = "Saidaliev";
var lastname = "Saidzoda";
console.log(lastname);
var isCompleted = true;
console.log(isCompleted);
var myBeloved = "Dilnoza";
var sentence = "my love is ".concat(myBeloved, ", who captured my heart");
console.log(sentence);
